### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by Lyncis** [Volentix/ledger-ui#1]
Create mockup for Ledger UI

**Comment by Lyncis** [comment]
This is how I was imagining this:

For user with the **PAYER** role, "Transfer" page.
Page content:
- Balance
- Choose a FromAccount (from which account transver VTX)
- Insert/type ToAccount (which account should receive VTX. Not sure what exactly should be entered here - a public key?)
- Amount. Number of points to be transferred
- Add Note. Add note to the transaction.
- Menu on the left. Leads to My Profile (contains information about the user if we need this), Transfer (current page), Transactions (view my previous transactions, can be implemented in the future).
When User presses "Send", transaction is created and it has to be confirmed by the Treasurer to be completed.

:
![screen shot 2018-08-23 at 2 38 40 pm](https://user-images.githubusercontent.com/8875863/44546992-a757b780-a6e7-11e8-8e37-05641c398acc.png)

**Treasurer**. Treasurer sees all the transactions that need his/her approval. Shows FromAccount, ToAccount, Amount:

![screen shot 2018-08-23 at 2 38 56 pm](https://user-images.githubusercontent.com/8875863/44547307-a6735580-a6e8-11e8-90ec-791e06b9f58d.png)

Treasurer can also see his profile and make a transfer.
Treasurer can see all transactions (in the future).

Transactions page shows all the transactions made by current user. It shows ToAccount, date (if we need this), amount and status.
Status "Completed" - transaction was confirmed by Treasurer and was completed.
Status "Pending" - transaction awaits for Treasurer confirmation, not completed.

![screen shot 2018-08-23 at 2 39 12 pm](https://user-images.githubusercontent.com/8875863/44547517-5cd73a80-a6e9-11e8-99d1-84a5403ed1ac.png)

**Comment by Lyncis** [comment]
@shawnlauzon please check this. I can change everything today or start implementing

**Comment by shawnlauzon** [comment]
This is great! The biggest thing missing is that there are two keys needed:

A) Account ID
B) User public key

Each transaction has Account ID (required) and User public key (optional). For example, to transfer VTX to a user, would be:

## From
Account: "EOS8TJpbWeQEoaMZMZzmo4SqC7DUucEUHRQJs1x7cXLcTqRhiJ7VF"
Key: undefined

## To: 
Account: "EOS6Ew693sd741xNhBPGaa72cujaaMByyJ7UBpWR5c9QnCsVcRuP4"
Key: "EOS5vBqi8YSzFCeTv4weRTwBzVkGCY5PN5Hm1Gp3133m8g9MtHTbW"

Having the account and key as drop-downs are excellent.
The user should also be able to enter a string rather than a drop-down

A few things:
- Change "points" to "VTX"
- We don't need a Profile (at this point)
- Needs to be a login
- "From account" instead of "FromAccount" (and others)

**Comment by shawnlauzon** [comment]
Awesome!
